import * as React from 'react';
import { Text } from 'office-ui-fabric-react';

interface ILoremIpsumProps {
  paragraphs: number;
}

const content = [
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aenean et tortor at risus viverra adipiscing at in. Gravida quis blandit turpis cursus in hac habitasse platea dictumst. Egestas pretium aenean pharetra magna. Amet nulla facilisi morbi tempus iaculis urna id. Ut tristique et egestas quis ipsum. Et egestas quis ipsum suspendisse ultrices gravida dictum. Ac felis donec et odio pellentesque diam volutpat commodo sed. Porttitor lacus luctus accumsan tortor posuere ac. Pretium nibh ipsum consequat nisl. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Vel risus commodo viverra maecenas. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Arcu felis bibendum ut tristique et egestas. Velit aliquet sagittis id consectetur purus ut. Proin fermentum leo vel orci porta non pulvinar neque. In hac habitasse platea dictumst vestibulum rhoncus est. Ultrices tincidunt arcu non sodales neque sodales ut.',
  'Id porta nibh venenatis cras sed felis. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Amet mauris commodo quis imperdiet massa tincidunt nunc. Sit amet justo donec enim. At varius vel pharetra vel turpis nunc eget lorem. Ut consequat semper viverra nam libero justo laoreet sit amet. Sodales ut etiam sit amet. Sagittis purus sit amet volutpat consequat mauris nunc. Arcu dui vivamus arcu felis bibendum ut tristique et. Donec enim diam vulputate ut pharetra sit. Turpis in eu mi bibendum neque egestas congue. Massa id neque aliquam vestibulum morbi blandit cursus risus at. Pellentesque nec nam aliquam sem et. Tortor at risus viverra adipiscing at in tellus integer feugiat. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Tincidunt nunc pulvinar sapien et ligula. Nunc aliquet bibendum enim facilisis gravida neque convallis. Mi ipsum faucibus vitae aliquet. Pretium fusce id velit ut tortor pretium.',
  'Feugiat nisl pretium fusce id velit ut tortor. Eleifend mi in nulla posuere sollicitudin. Quis risus sed vulputate odio ut. Volutpat lacus laoreet non curabitur gravida arcu ac. Accumsan lacus vel facilisis volutpat est. Sed adipiscing diam donec adipiscing tristique risus nec feugiat in. Nunc congue nisi vitae suscipit tellus mauris. Orci ac auctor augue mauris augue neque gravida in. Metus dictum at tempor commodo ullamcorper a lacus. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Dictumst quisque sagittis purus sit amet volutpat consequat mauris nunc. In mollis nunc sed id semper. Cras tincidunt lobortis feugiat vivamus at augue eget. Cursus euismod quis viverra nibh. Tempus egestas sed sed risus pretium. In cursus turpis massa tincidunt dui. Aliquet eget sit amet tellus cras adipiscing. Cursus turpis massa tincidunt dui.',
  'Amet consectetur adipiscing elit ut aliquam purus sit. Egestas pretium aenean pharetra magna ac. Dictum at tempor commodo ullamcorper a. Amet risus nullam eget felis eget nunc lobortis mattis. Curabitur gravida arcu ac tortor dignissim convallis aenean et tortor. Quisque non tellus orci ac auctor augue. Neque ornare aenean euismod elementum nisi quis eleifend. A pellentesque sit amet porttitor eget. Enim blandit volutpat maecenas volutpat blandit aliquam etiam. Vitae semper quis lectus nulla at volutpat diam ut. Ipsum dolor sit amet consectetur adipiscing elit. Egestas sed sed risus pretium quam. Eu facilisis sed odio morbi. Ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Tincidunt augue interdum velit euismod in pellentesque massa placerat. Adipiscing enim eu turpis egestas pretium aenean pharetra magna. In metus vulputate eu scelerisque felis imperdiet proin.',
  'Maecenas accumsan lacus vel facilisis volutpat. Posuere lorem ipsum dolor sit amet consectetur. Platea dictumst quisque sagittis purus sit amet volutpat. Iaculis nunc sed augue lacus viverra vitae. Id interdum velit laoreet id donec ultrices tincidunt arcu non. Sagittis aliquam malesuada bibendum arcu vitae. In nulla posuere sollicitudin aliquam ultrices sagittis orci. Nunc aliquet bibendum enim facilisis gravida. Amet nulla facilisi morbi tempus iaculis urna id volutpat lacus. Suspendisse sed nisi lacus sed viverra tellus in hac habitasse. Ultrices mi tempus imperdiet nulla malesuada pellentesque. Aliquam ut porttitor leo a diam sollicitudin. Massa placerat duis ultricies lacus sed turpis. Lacus viverra vitae congue eu consequat. Viverra maecenas accumsan lacus vel facilisis volutpat est. Commodo ullamcorper a lacus vestibulum sed. Quis lectus nulla at volutpat diam. Convallis a cras semper auctor. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Tempor commodo ullamcorper a lacus.',
  'Fringilla urna porttitor rhoncus dolor purus non enim praesent elementum. Aliquam etiam erat velit scelerisque in dictum. Massa sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ornare massa eget egestas purus viverra accumsan in nisl nisi. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. Tristique magna sit amet purus. Enim nulla aliquet porttitor lacus luctus accumsan. Amet mauris commodo quis imperdiet. At elementum eu facilisis sed odio morbi quis commodo odio. Duis tristique sollicitudin nibh sit amet commodo nulla. Odio euismod lacinia at quis risus sed vulputate. Fermentum odio eu feugiat pretium nibh ipsum consequat. In arcu cursus euismod quis viverra nibh cras. In aliquam sem fringilla ut. In massa tempor nec feugiat nisl pretium. Quis risus sed vulputate odio ut enim. Pharetra et ultrices neque ornare.',
  'Ac placerat vestibulum lectus mauris ultrices eros in cursus. Consectetur adipiscing elit duis tristique. Id ornare arcu odio ut sem nulla pharetra diam sit. Id donec ultrices tincidunt arcu non sodales neque. Scelerisque felis imperdiet proin fermentum leo. Mi quis hendrerit dolor magna eget est lorem ipsum dolor. Eget nullam non nisi est. Tellus orci ac auctor augue mauris augue. Ultrices sagittis orci a scelerisque purus semper eget duis at. Nisi quis eleifend quam adipiscing. Nisl vel pretium lectus quam id. Amet risus nullam eget felis eget nunc lobortis.',
  'Nibh tellus molestie nunc non blandit massa enim nec. Pharetra et ultrices neque ornare. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue eget. Amet cursus sit amet dictum sit amet justo. Velit dignissim sodales ut eu sem. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Lectus magna fringilla urna porttitor rhoncus dolor purus non. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Ac feugiat sed lectus vestibulum mattis ullamcorper velit. Ac felis donec et odio pellentesque diam volutpat commodo.',
  'Nec dui nunc mattis enim ut. Eleifend mi in nulla posuere sollicitudin aliquam. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Vestibulum morbi blandit cursus risus at ultrices mi tempus imperdiet. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Neque ornare aenean euismod elementum nisi quis. Hac habitasse platea dictumst vestibulum rhoncus. Mauris pharetra et ultrices neque ornare aenean. Pellentesque sit amet porttitor eget dolor morbi non. Faucibus in ornare quam viverra orci sagittis. Nulla aliquet porttitor lacus luctus accumsan. Suscipit adipiscing bibendum est ultricies. Aliquam ut porttitor leo a diam. Commodo sed egestas egestas fringilla phasellus. Viverra orci sagittis eu volutpat odio facilisis mauris. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Maecenas volutpat blandit aliquam etiam.',
  'Lorem ipsum dolor sit amet consectetur adipiscing elit. Habitasse platea dictumst quisque sagittis purus. Elementum sagittis vitae et leo. Amet dictum sit amet justo. Sagittis aliquam malesuada bibendum arcu. Aliquam sem fringilla ut morbi tincidunt augue interdum. Tortor pretium viverra suspendisse potenti. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Nulla facilisi cras fermentum odio eu. Semper eget duis at tellus at urna. Aliquam nulla facilisi cras fermentum odio. Porttitor rhoncus dolor purus non enim.'
];

const paragraphs = (count: number): string[] => {
  const result = [];
  for (let i = 0; i < count; i++) {
    result.push(content[i % content.length]);
  }
  return result;
};

export const LoremIpsum: React.FunctionComponent<ILoremIpsumProps> = (props: ILoremIpsumProps) => {
  return (
    <>
      {paragraphs(props.paragraphs).map((x, i) => (
        <p key={i}>
          <Text>{x}</Text>
        </p>
      ))}
    </>
  );
};
